/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CompoundAction: typeof import('./src/components/CompoundAction.vue')['default']
    FooterComp: typeof import('./src/components/FooterComp.vue')['default']
    LangChooser: typeof import('./src/components/LangChooser.vue')['default']
    MainComp: typeof import('./src/components/MainComp.vue')['default']
    OccurrenceCarousel: typeof import('./src/components/OccurrenceCarousel.vue')['default']
    OrderCarousel: typeof import('./src/components/OrderCarousel.vue')['default']
    QuestionCarousel: typeof import('./src/components/QuestionCarousel.vue')['default']
    ReviewCarousel: typeof import('./src/components/ReviewCarousel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
