/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FooterComp: typeof import('./src/components/FooterComp.vue')['default']
    LangChooser: typeof import('./src/components/LangChooser.vue')['default']
    MainCarousel: typeof import('./src/components/MainCarousel.vue')['default']
    MainComp: typeof import('./src/components/MainComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
